### ISSUE TITLE
Node.js libraries require @opencensus/propagation-tracecontext but it is not in package.json

### ISSUE THREAD

**Issue by aabmass** [google/sqlcommenter#23]
`index.js` (for both knex and sequelize integration) requires `util.js` which requires `@opencensus/propagation-tracecontext`. 

https://github.com/google/sqlcommenter/blob/5adcedb785e12919f1b3dc72cee1f32896ff4a89/nodejs/sqlcommenter-nodejs/packages/sqlcommenter-knex/util.js#L15

However, this dep is only in devDependencies atm. OpenCensus or OpenTelemetry are providers for tracestate/traceparent, so the dependency should be optional and only crash if the user passes tracestate/traceparent in their config.

Repro:
```console
$ npm init -y
$ npm install @google-cloud/sqlcommenter-knex
$ node -i "require('@google-cloud/sqlcommenter-knex')"
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/usr/local/google/home/aaronabbott/repo/sqlcommenter/nodejs/sqlcommenter-nodejs/samples/express-opentelemetry/require('@google-cloud/sqlcommenter-knex')'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by aabmass** [comment]
I added the missing deps to `peerDependencies` in #26, so now the user knows to install these. However, they should really be optional depending on if the user is using this feature.
