### ISSUE TITLE
Import fails on Python 3.12, pkg_resources removed

### ISSUE THREAD

**Issue by jwhitlock** [google/sqlcommenter#275]
If you are running Python 3.11 with warnings enabled, you get a deprecation warning:

```sh
python3.11 -m pip install google-cloud-sqlcommenter==2.0.0
python3.11 -Wall -c "import google.cloud.sqlcommenter"
```
```pycon
/Users/jwhitlock/.virtualenvs/my_p11_venv/lib/python3.11/site-packages/google/__init__.py:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').declare_namespace(__name__)
/Users/jwhitlock/.virtualenvs/my_p11_venv/lib/python3.11/site-packages/google/__init__.py:17: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  __import__('pkg_resources').declare_namespace(__name__)
```

`pkg_resources` was removed in Python 3.12, so you get an error:

```sh
python3.11 -m pip install google-cloud-sqlcommenter==2.0.0
python3.12 -Wall -c "import google.cloud.sqlcommenter"
```
```pycon
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jwhitlock/.virtualenvs/my_p12_venv/lib/python3.12/site-packages/google/__init__.py", line 17, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by jwhitlock** [comment]
The error is because `pkg_resources` is no longer installed by default in a virtualenv. Installing `setuptools` fixes the issue, but can cause problems if you are _not_ in a virtualenv. I've updated the issue to be more precise. 

The issue would be fixed by no longer declaring a namespace, as suggested in the links in the `DeprecationWarning`.
